// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/GCL.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class GCL {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=60;
      Object Q=$fix(GCollections.asSet("ST","B","G","LP1","exp1","cmm1","RP1","I","cond","Num","T1","T2","Asig2","col2","eq2","Call2","LP2","exp2","exp3","cmm2","RP2","Val2","L","Asig3","col3","eq3","Call3","LP3","Val3","RP3","exp4","exp5","cmm3","EN","Err"));
      $line=63;
      Object \u03A3=$fix(GCollections.asSet('B','g','(',')','a','b',',','I','T','=','1','2','3','4','5','6','7','8','9','0',':','+','-','*','/','%','E'));
      $line=65;
      Object q=$fix("ST");
      $line=66;
      Object F=$fix(GCollections.asSet("EN","Err"));
      $line=67;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(GCL.class,"\u03B4")})));
      $line=68;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,GCL.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=72;
      if (($opEqualY(q,"ST")&&$opEqualY(\u03C3,'B'))) {
        $line=73;
        $result="B";
        if (true) break $try;
      }
      else {
        $line=75;
        if (($opEqualY(q,"B")&&$opEqualY(\u03C3,'g'))) {
          $line=76;
          $result="G";
          if (true) break $try;
        }
        else {
          $line=78;
          if (($opEqualY(q,"G")&&$opEqualY(\u03C3,'('))) {
            $line=79;
            $result="LP1";
            if (true) break $try;
          }
          else {
            $line=81;
            if (($opEqualY(q,"LP1")&&$bool(($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))))) {
              $line=82;
              $result="exp1";
              if (true) break $try;
            }
            else {
              $line=83;
              if (($opEqualY(q,"LP1")&&$opEqualY(\u03C3,')'))) {
                $line=84;
                $result="RP1";
                if (true) break $try;
              }
              else {
                $line=86;
                if (($opEqualY(q,"exp1")&&$opEqualY(\u03C3,','))) {
                  $line=87;
                  $result="cmm1";
                  if (true) break $try;
                }
                else {
                  $line=88;
                  if (($opEqualY(q,"exp1")&&$opEqualY(\u03C3,')'))) {
                    $line=89;
                    $result="RP1";
                    if (true) break $try;
                  }
                  else {
                    $line=91;
                    if (($opEqualY(q,"cmm1")&&$bool(($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))))) {
                      $line=92;
                      $result="exp1";
                      if (true) break $try;
                    }
                    else {
                      $line=94;
                      if (($opEqualY(q,"RP1")&&$opEqualY(\u03C3,'I'))) {
                        $line=95;
                        $result="I";
                        if (true) break $try;
                      }
                      else {
                        $line=96;
                        if (($opEqualY(q,"RP1")&&$opEqualY(\u03C3,'E'))) {
                          $line=97;
                          $result="EN";
                          if (true) break $try;
                        }
                        else {
                          $line=99;
                          if (($opEqualY(q,"I")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                            $line=101;
                            $result="cond";
                            if (true) break $try;
                          }
                          else {
                            $line=103;
                            if (($opEqualY(q,"cond")&&$opEqualY(\u03C3,'='))) {
                              $line=104;
                              $result="Num";
                              if (true) break $try;
                            }
                            else {
                              $line=106;
                              if (($opEqualY(q,"Num")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                $line=108;
                                $result="T1";
                                if (true) break $try;
                              }
                              else {
                                $line=110;
                                if (($opEqualY(q,"T1")&&$opEqualY(\u03C3,'T'))) {
                                  $line=111;
                                  $result="T2";
                                  if (true) break $try;
                                }
                                else {
                                  $line=113;
                                  if (($opEqualY(q,"T2")&&$opEqualY(\u03C3,'g'))) {
                                    $line=114;
                                    $result="Asig2";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=116;
                                    if (($opEqualY(q,"Asig2")&&$opEqualY(\u03C3,':'))) {
                                      $line=117;
                                      $result="col2";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=119;
                                      if (($opEqualY(q,"col2")&&$opEqualY(\u03C3,'='))) {
                                        $line=120;
                                        $result="eq2";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=122;
                                        if (($opEqualY(q,"eq2")&&$opEqualY(\u03C3,'g'))) {
                                          $line=123;
                                          $result="Call2";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=124;
                                          if (($opEqualY(q,"eq2")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                            $line=126;
                                            $result="Val2";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=128;
                                            if (($opEqualY(q,"Call2")&&$opEqualY(\u03C3,'('))) {
                                              $line=129;
                                              $result="LP2";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=131;
                                              if (($opEqualY(q,"LP2")&&$opEqualY(\u03C3,')'))) {
                                                $line=132;
                                                $result="RP2";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=133;
                                                if (($opEqualY(q,"LP2")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                  $line=135;
                                                  $result="exp2";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=137;
                                                  if (($opEqualY(q,"exp2")&&$bool((((($opEqualY(\u03C3,'+')||$opEqualY(\u03C3,'-'))||$opEqualY(\u03C3,'*'))||$opEqualY(\u03C3,'/'))||$opEqualY(\u03C3,'%'))))) {
                                                    $line=138;
                                                    $result="exp3";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=139;
                                                    if (($opEqualY(q,"exp2")&&$opEqualY(\u03C3,','))) {
                                                      $line=140;
                                                      $result="cmm2";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=141;
                                                      if (($opEqualY(q,"exp2")&&$opEqualY(\u03C3,')'))) {
                                                        $line=142;
                                                        $result="RP2";
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=144;
                                                        if (($opEqualY(q,"exp3")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                          $line=146;
                                                          $result="exp2";
                                                          if (true) break $try;
                                                        }
                                                        else {
                                                          $line=148;
                                                          if (($opEqualY(q,"cmm2")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                            $line=150;
                                                            $result="exp2";
                                                            if (true) break $try;
                                                          }
                                                          else {
                                                            $line=152;
                                                            if (($opEqualY(q,"RP2")&&$opEqualY(\u03C3,'E'))) {
                                                              $line=153;
                                                              $result="L";
                                                              if (true) break $try;
                                                            }
                                                            else {
                                                              $line=155;
                                                              if (($opEqualY(q,"Val2")&&$opEqualY(\u03C3,'E'))) {
                                                                $line=156;
                                                                $result="L";
                                                                if (true) break $try;
                                                              }
                                                              else {
                                                                $line=158;
                                                                if (($opEqualY(q,"L")&&$opEqualY(\u03C3,'g'))) {
                                                                  $line=159;
                                                                  $result="Asig3";
                                                                  if (true) break $try;
                                                                }
                                                                else {
                                                                  $line=161;
                                                                  if (($opEqualY(q,"Asig3")&&$opEqualY(\u03C3,':'))) {
                                                                    $line=162;
                                                                    $result="col3";
                                                                    if (true) break $try;
                                                                  }
                                                                  else {
                                                                    $line=164;
                                                                    if (($opEqualY(q,"col3")&&$opEqualY(\u03C3,'='))) {
                                                                      $line=165;
                                                                      $result="eq3";
                                                                      if (true) break $try;
                                                                    }
                                                                    else {
                                                                      $line=167;
                                                                      if (($opEqualY(q,"eq3")&&$opEqualY(\u03C3,'g'))) {
                                                                        $line=168;
                                                                        $result="Call3";
                                                                        if (true) break $try;
                                                                      }
                                                                      else {
                                                                        $line=169;
                                                                        if (($opEqualY(q,"eq3")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                                          $line=171;
                                                                          $result="Val3";
                                                                          if (true) break $try;
                                                                        }
                                                                        else {
                                                                          $line=173;
                                                                          if (($opEqualY(q,"Val3")&&$opEqualY(\u03C3,')'))) {
                                                                            $line=174;
                                                                            $result="RP3";
                                                                            if (true) break $try;
                                                                          }
                                                                          else {
                                                                            $line=176;
                                                                            if (($opEqualY(q,"Call3")&&$opEqualY(\u03C3,'('))) {
                                                                              $line=177;
                                                                              $result="LP3";
                                                                              if (true) break $try;
                                                                            }
                                                                            else {
                                                                              $line=179;
                                                                              if (($opEqualY(q,"LP3")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                                                $line=181;
                                                                                $result="exp4";
                                                                                if (true) break $try;
                                                                              }
                                                                              else {
                                                                                $line=183;
                                                                                if (($opEqualY(q,"exp4")&&$bool((((($opEqualY(\u03C3,'+')||$opEqualY(\u03C3,'-'))||$opEqualY(\u03C3,'*'))||$opEqualY(\u03C3,'/'))||$opEqualY(\u03C3,'%'))))) {
                                                                                  $line=184;
                                                                                  $result="exp5";
                                                                                  if (true) break $try;
                                                                                }
                                                                                else {
                                                                                  $line=185;
                                                                                  if (($opEqualY(q,"exp4")&&$opEqualY(\u03C3,','))) {
                                                                                    $line=186;
                                                                                    $result="cmm3";
                                                                                    if (true) break $try;
                                                                                  }
                                                                                  else {
                                                                                    $line=187;
                                                                                    if (($opEqualY(q,"exp4")&&$opEqualY(\u03C3,')'))) {
                                                                                      $line=188;
                                                                                      $result="RP3";
                                                                                      if (true) break $try;
                                                                                    }
                                                                                    else {
                                                                                      $line=190;
                                                                                      if (($opEqualY(q,"exp5")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                                                        $line=192;
                                                                                        $result="exp4";
                                                                                        if (true) break $try;
                                                                                      }
                                                                                      else {
                                                                                        $line=194;
                                                                                        if (($opEqualY(q,"cmm3")&&$bool(((((((((((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9'))||$opEqualY(\u03C3,'0'))))) {
                                                                                          $line=196;
                                                                                          $result="exp4";
                                                                                          if (true) break $try;
                                                                                        }
                                                                                        else {
                                                                                          $line=198;
                                                                                          if (($opEqualY(q,"RP3")&&$opEqualY(\u03C3,'E'))) {
                                                                                            $line=199;
                                                                                            $result="EN";
                                                                                            if (true) break $try;
                                                                                          }
                                                                                          else {
                                                                                            $line=200;
                                                                                            if (($opEqualY(q,"RP3")&&$opEqualY(\u03C3,'I'))) {
                                                                                              $line=201;
                                                                                              $result="I";
                                                                                              if (true) break $try;
                                                                                            }
                                                                                            else {
                                                                                              $line=203;
                                                                                              if (($opEqualY(q,"EN")&&$opEqualY(\u03C3,'B'))) {
                                                                                                $line=204;
                                                                                                $result="B";
                                                                                                if (true) break $try;
                                                                                              }
                                                                                              else {
                                                                                                $line=209;
                                                                                                $result="Err";
                                                                                                if (true) break $try;
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=211;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,GCL.class,"\u03B4",$line);
    }
    return $result;
  }
}
